# Generated by Django 4.2.5 on 2023-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usn", models.CharField(max_length=12)),
                ("password", models.CharField(max_length=10)),
                (
                    "question_number",
                    models.PositiveIntegerField(blank=True, max_length=2),
                ),
            ],
        ),
    ]
